version: "3.9"

services:
  django:
    container_name: django_container
    build: .
    command: python3 /bookgiveaway/manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/bookgiveaway
    ports:
      - 8000:8000
    env_file:
      - environment-variables.env
    depends_on:
      - db
  
  db:
    container_name: postgres_container
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: