# Generated by Django 4.0.10 on 2023-09-27 19:34

import books.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("author", models.CharField(max_length=100)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Fiction", "Fiction"),
                            ("Non-Fiction", "Non-Fiction"),
                            ("Mystery", "Mystery"),
                            ("Romance", "Romance"),
                            ("Science Fiction", "Science Fiction"),
                            ("Fantasy", "Fantasy"),
                            ("Thriller", "Thriller"),
                            ("Horror", "Horror"),
                            ("Biography", "Biography"),
                            ("Autobiography", "Autobiography"),
                        ],
                        max_length=100,
                    ),
                ),
                ("ISBN", models.CharField(max_length=13, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[("Brand New", "Brand New"), ("Used", "Used")],
                        default="Brand New",
                        max_length=10,
                    ),
                ),
                (
                    "book_cover",
                    models.ImageField(
                        blank=True, upload_to=books.models.Book.book_cover_filename
                    ),
                ),
                ("available", models.BooleanField(default=True)),
                ("location", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
