# Generated by Django 4.0.10 on 2023-09-28 20:42

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_genre_alter_book_description_alter_book_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_cover",
            field=models.ImageField(
                blank=True, null=True, upload_to=books.models.Book.book_cover_filename
            ),
        ),
    ]
