# Generated by Django 4.0.10 on 2023-09-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_alter_book_book_cover"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="location",
            new_name="retrieval_location",
        ),
        migrations.RemoveField(
            model_name="book",
            name="genre",
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(to="books.genre"),
        ),
    ]
