# Generated by Django 4.0.10 on 2023-09-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_rename_location_book_retrieval_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=100, unique=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("author_info", models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(to="books.author"),
        ),
    ]
