# Generated by Django 4.0.10 on 2023-09-30 06:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_author_remove_book_author_book_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="author_info",
        ),
        migrations.RemoveField(
            model_name="author",
            name="country",
        ),
        migrations.RemoveField(
            model_name="author",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="genre",
            name="genre_description",
        ),
    ]
