# Generated by Django 4.0.10 on 2023-10-01 02:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookingrequests", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingrequest",
            name="request_selected",
        ),
        migrations.RemoveField(
            model_name="bookingrequest",
            name="status",
        ),
    ]
